/**
 * Client-side report generation: structured, printable documents and CSV
 * exports. Everything here runs in the browser — no server round trip — and is
 * deliberately dependency-free so an export keeps working offline.
 *
 * Shared by the bird profile, the fight history and the dashboard so every
 * "Export" / "Print" button produces the same kind of structured report.
 */

export type ReportField = { label: string; value: string };

export type ReportTable = {
  heading?: string;
  columns: string[];
  rows: (string | number | null | undefined)[][];
};

export type ReportSection = {
  heading: string;
  fields?: ReportField[];
  table?: ReportTable;
};

export type ReportDocument = {
  title: string;
  meta?: string;
  sections: ReportSection[];
};

export function escapeHtml(value: string): string {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

const cell = (value: string | number | null | undefined): string =>
  value === null || value === undefined || value === '' ? '—' : String(value);

/** RFC 4180 CSV: quoted fields, doubled quotes, CRLF line endings, UTF-8 BOM. */
export function toCsv(rows: (string | number | null | undefined)[][]): string {
  const body = rows
    .map((row) =>
      row
        .map((raw) => {
          const value = cell(raw);
          return /[",\r\n]/.test(value) ? `"${value.replace(/"/g, '""')}"` : value;
        })
        .join(','),
    )
    .join('\r\n');
  return `﻿${body}`;
}

export function downloadCsv(filename: string, rows: (string | number | null | undefined)[][]): void {
  const blob = new Blob([toCsv(rows)], { type: 'text/csv;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename.endsWith('.csv') ? filename : `${filename}.csv`;
  document.body.appendChild(link);
  link.click();
  link.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function buildReportHtml(doc: ReportDocument): string {
  const generated = new Date().toLocaleString();

  const sections = doc.sections
    .map((section) => {
      const fields = section.fields?.length
        ? `<dl class="fields">${section.fields
            .map(
              (f) =>
                `<div class="row"><dt>${escapeHtml(f.label)}</dt><dd>${escapeHtml(f.value)}</dd></div>`,
            )
            .join('')}</dl>`
        : '';

      const table = section.table
        ? `<table><thead><tr>${section.table.columns
            .map((c) => `<th>${escapeHtml(c)}</th>`)
            .join('')}</tr></thead><tbody>${section.table!.rows
            .map((r) => `<tr>${r.map((v) => `<td>${escapeHtml(cell(v))}</td>`).join('')}</tr>`)
            .join('')}</tbody></table>`
        : '';

      return `<section><h2>${escapeHtml(section.heading)}</h2>${fields}${table}</section>`;
    })
    .join('');

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>${escapeHtml(doc.title)}</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: ui-sans-serif, system-ui, -apple-system, 'Segoe UI', sans-serif; color: #0f172a; margin: 32px; font-size: 12px; }
  header { border-bottom: 3px solid #059669; padding-bottom: 12px; margin-bottom: 20px; }
  h1 { font-size: 20px; margin: 0 0 4px; letter-spacing: -0.02em; }
  .meta { color: #475569; font-size: 11px; margin: 0; }
  section { margin-bottom: 18px; page-break-inside: avoid; }
  h2 { font-size: 12px; text-transform: uppercase; letter-spacing: 0.1em; color: #059669; margin: 0 0 8px; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px; }
  .fields { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 4px 24px; margin: 0; }
  .row { display: flex; gap: 8px; border-bottom: 1px dotted #e2e8f0; padding: 3px 0; }
  dt { font-weight: 700; color: #475569; min-width: 120px; margin: 0; }
  dd { margin: 0; flex: 1; }
  table { width: 100%; border-collapse: collapse; margin-top: 6px; }
  th, td { border: 1px solid #e2e8f0; padding: 5px 7px; text-align: left; }
  th { background: #f1f5f9; font-size: 10px; text-transform: uppercase; letter-spacing: 0.06em; }
  footer { margin-top: 24px; border-top: 1px solid #e2e8f0; padding-top: 8px; color: #64748b; font-size: 10px; }
  @media print { body { margin: 0; } }
</style>
</head>
<body>
<header>
  <h1>${escapeHtml(doc.title)}</h1>
  ${doc.meta ? `<p class="meta">${escapeHtml(doc.meta)}</p>` : ''}
  <p class="meta">GalloTrack structured report · Generated ${escapeHtml(generated)}</p>
</header>
${sections}
<footer>Generated by GalloTrack. Win rate is wins ÷ (wins + losses); draws are excluded.</footer>
<script>window.addEventListener('load', function () { window.focus(); window.print(); });<\/script>
</body>
</html>`;
}

/**
 * Render the report into a hidden iframe and hand it straight to the print
 * dialog (the user can then "Save as PDF"). An iframe is used instead of a
 * popup window because popup blockers routinely swallow `window.open`.
 */
export function printReport(doc: ReportDocument): void {
  const html = buildReportHtml(doc);
  const frame = document.createElement('iframe');
  frame.setAttribute('aria-hidden', 'true');
  frame.setAttribute('title', doc.title);
  frame.style.cssText = 'position:fixed;right:0;bottom:0;width:0;height:0;border:0;visibility:hidden';
  document.body.appendChild(frame);

  const win = frame.contentWindow;
  if (!win) {
    frame.remove();
    return;
  }
  win.document.open();
  win.document.write(html);
  win.document.close();
  // The report calls print() itself on load; drop the frame afterwards so a
  // second export starts clean.
  setTimeout(() => frame.remove(), 60000);
}
