-- ==============================================================================
-- GALLOTRACK: STANDARDIZED BIRD CODES + BLOODLINE COMPOSITION (idempotent)
-- ==============================================================================
-- Run this in the Supabase SQL Editor once. It:
--   1. Adds `bird_code` — the standardized tag the adviser asked for:
--        Sires     -> 1A, 2A, 3A ...   (A = sire / male line)
--        Dams      -> 1B, 2B, 3B ...   (B = dam / female line)
--        Offspring -> parent-code combination, e.g. 1Ax1B (-2, -3 for clutch mates)
--      Codes are auto-generated by the app but may be overridden by the breeder.
--   2. Adds `bloodline_composition` (jsonb) — the per-strain blood percentage
--      breakdown, e.g. {"Kelso": 50, "Hatch": 25, "Roundhead": 25}.
--      Written by the app on every insert/update using the 50/50 inheritance rule.
--   3. Backfills `bird_code` for legacy rows so every bird is tagged at once.
--   4. Adds uniqueness + lookup indexes for pedigree lookups.
-- All statements are idempotent.
-- ==============================================================================

-- ── 1. New columns ──────────────────────────────────────────────────────────
ALTER TABLE fowl ADD COLUMN IF NOT EXISTS bird_code text;
ALTER TABLE fowl ADD COLUMN IF NOT EXISTS bloodline_composition jsonb;

COMMENT ON COLUMN fowl.bird_code IS
  'Standardized tag: 1A/2A (sire line), 1B/2B (dam line), 1Ax1B (offspring of 1A x 1B). Auto-generated, manually overridable.';
COMMENT ON COLUMN fowl.bloodline_composition IS
  'Per-strain blood percentage breakdown computed from ancestry, e.g. {"Kelso": 50, "Hatch": 25, "Roundhead": 25}. Sums to 100.';

-- ── 2. Backfill missing bird codes (legacy rows) ───────────────────────────
-- Numbering restarts per owner, matching how the app scopes codes per user.
DO $$
DECLARE
  u RECORD;
  seq_a integer;
  seq_b integer;
  r RECORD;
  new_code text;
BEGIN
  FOR u IN SELECT DISTINCT user_id FROM fowl ORDER BY 1 LOOP
    SELECT COALESCE(MAX(n), 0) INTO seq_a
      FROM (
        SELECT regexp_replace(bird_code, '[^0-9]', '', 'g')::integer AS n
          FROM fowl
         WHERE user_id IS NOT DISTINCT FROM u.user_id AND bird_code ~ '^[0-9]+A$'
      ) existing_a;

    SELECT COALESCE(MAX(n), 0) INTO seq_b
      FROM (
        SELECT regexp_replace(bird_code, '[^0-9]', '', 'g')::integer AS n
          FROM fowl
         WHERE user_id IS NOT DISTINCT FROM u.user_id AND bird_code ~ '^[0-9]+B$'
      ) existing_b;

    FOR r IN
      SELECT id, gender
        FROM fowl
       WHERE user_id IS NOT DISTINCT FROM u.user_id
         AND (bird_code IS NULL OR btrim(bird_code) = '')
       ORDER BY id
    LOOP
      IF lower(coalesce(r.gender, '')) IN ('hen', 'pullet', 'female') THEN
        seq_b := seq_b + 1;
        new_code := seq_b::text || 'B';
      ELSE
        seq_a := seq_a + 1;
        new_code := seq_a::text || 'A';
      END IF;

      UPDATE fowl SET bird_code = new_code WHERE id = r.id;
    END LOOP;
  END LOOP;
END $$;

-- ── 3. Uniqueness: one code per bird, per owner ────────────────────────────
CREATE UNIQUE INDEX IF NOT EXISTS fowl_user_bird_code_key
  ON fowl (user_id, lower(bird_code))
  WHERE bird_code IS NOT NULL AND btrim(bird_code) <> '';

-- ── 4. Pedigree lookup indexes (parent links are free-text names) ──────────
CREATE INDEX IF NOT EXISTS fowl_lower_sire_idx ON fowl (lower(sire));
CREATE INDEX IF NOT EXISTS fowl_lower_dam_idx  ON fowl (lower(dam));
CREATE INDEX IF NOT EXISTS fowl_lower_name_idx ON fowl (lower(name));

-- ==============================================================================
-- POST-RUN VERIFICATION (run this yourself afterwards)
-- ==============================================================================
-- SELECT bird_code, name, gender, bloodline_pct, bloodline_composition
--   FROM fowl ORDER BY id;
-- SELECT user_id, lower(bird_code) AS code, count(*)
--   FROM fowl GROUP BY 1, 2 HAVING count(*) > 1;
-- ==============================================================================
