-- ==============================================================================
-- GALLOTRACK: M1 - REGISTRY, LIFECYCLE STATUS & CONFIGURABLE OPTION LISTS
-- (idempotent, re-run safe)
--
-- User feedback: the four status concepts must stay SEPARATE, and injured
-- birds must NEVER be converted into breeders automatically:
--   condition_status : injury/health after a match (Fit ... Deceased)
--   breeding_role    : none | breeder | material   (manual only)
--   activity_status  : active | inactive           (alive but not in use)
--   archive_kind     : sold | transfer | inactive | retired | other
--   retired_scope    : fighting | breeding | both  (picker per record)
-- `fowl.status` stays the canonical display label so existing badges/filters
-- keep working; app writes keep the new columns in sync.
--
-- Also adds:
--   fowl_status_history : append-only audit log ("status history" timeline)
--   registry_options    : user-editable lists (event/class/condition/reason/
--                         retired scope/location) with global templates
--   user_settings       : per-farm config keys (ranking metric, whether
--                         location is required, family headline count, ...)
--   match.fowl_id / match.opponent_id : lineage links (entry_name/opponent
--                         remain display snapshots)
-- ==============================================================================

-- ═══════════════════════════════════════════════════════════════════════════
-- 1. fowl: new orthogonal lifecycle columns
-- ═══════════════════════════════════════════════════════════════════════════

ALTER TABLE fowl ADD COLUMN IF NOT EXISTS notes           TEXT;
ALTER TABLE fowl ADD COLUMN IF NOT EXISTS condition_status TEXT NOT NULL DEFAULT 'Fit / Recovered';
ALTER TABLE fowl ADD COLUMN IF NOT EXISTS breeding_role   TEXT NOT NULL DEFAULT 'none';
ALTER TABLE fowl ADD COLUMN IF NOT EXISTS activity_status TEXT NOT NULL DEFAULT 'active';
ALTER TABLE fowl ADD COLUMN IF NOT EXISTS archive_kind    TEXT;
ALTER TABLE fowl ADD COLUMN IF NOT EXISTS retired_scope   TEXT;
ALTER TABLE fowl ADD COLUMN IF NOT EXISTS return_date     DATE;

-- ═══════════════════════════════════════════════════════════════════════════
-- 2. Backfill from existing registry state (run once, but re-run safe:
--    every UPDATE only touches rows that still look unmigrated)
-- ═══════════════════════════════════════════════════════════════════════════

-- 2a. Archived birds -> structured archive kind (free-text reason preserved)
UPDATE fowl SET archive_kind = CASE
    WHEN lower(COALESCE(archive_reason, '')) LIKE 'sold%'      THEN 'sold'
    WHEN lower(COALESCE(archive_reason, '')) LIKE 'transfer%'  THEN 'transfer'
    WHEN lower(COALESCE(archive_reason, '')) LIKE 'inactive%'  THEN 'inactive'
    WHEN lower(COALESCE(archive_reason, '')) LIKE 'retired%'   THEN 'retired'
    WHEN btrim(COALESCE(archive_reason, '')) <> ''             THEN 'other'
    ELSE NULL
  END
  WHERE status = 'Archived' AND archive_kind IS NULL;

-- 2b. Retired birds -> which career ended (fighting / breeding)
UPDATE fowl SET retired_scope = CASE
    WHEN lower(COALESCE(archive_reason, '')) LIKE 'retired from breeding%' THEN 'breeding'
    ELSE 'fighting'
  END
  WHERE archive_kind = 'retired' AND retired_scope IS NULL;

-- 2c. Deceased birds -> injury condition agrees with lifecycle (atomic by app)
UPDATE fowl SET condition_status = 'Deceased'
  WHERE status = 'Deceased' AND condition_status <> 'Deceased';

-- 2d. 'Sire Material' (legacy status) -> breeding role, still active
UPDATE fowl SET breeding_role = 'material'
  WHERE status = 'Sire Material' AND breeding_role = 'none';

-- 2e. Not-in-use birds -> inactive activity
UPDATE fowl SET activity_status = 'inactive'
  WHERE status IN ('Archived', 'Inactive', 'Deceased') AND activity_status = 'active';

-- 2f. Structural enums get a CHECK (only after the data is clean)
ALTER TABLE fowl DROP CONSTRAINT IF EXISTS fowl_breeding_role_check;
ALTER TABLE fowl
  ADD CONSTRAINT fowl_breeding_role_check CHECK (breeding_role IN ('none', 'breeder', 'material'));

ALTER TABLE fowl DROP CONSTRAINT IF EXISTS fowl_activity_status_check;
ALTER TABLE fowl
  ADD CONSTRAINT fowl_activity_status_check CHECK (activity_status IN ('active', 'inactive'));

-- No CHECK on condition_status / archive_kind / retired_scope: those come from
-- the editable registry_options lists (history rows must always be storable).

-- ═══════════════════════════════════════════════════════════════════════════
-- 3. fowl_status_history - append-only status change log
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS fowl_status_history (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fowl_id    BIGINT NOT NULL REFERENCES fowl(id) ON DELETE CASCADE,
  field      TEXT NOT NULL,               -- status | condition_status | breeding_role | activity_status | archive_kind | retired_scope
  old_value  TEXT,
  new_value  TEXT NOT NULL,
  reason     TEXT,                        -- archive / death reason label
  note       TEXT,
  changed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  changed_by UUID                         -- auth.uid() of the editor
);

CREATE INDEX IF NOT EXISTS idx_fowl_status_history_fowl
  ON fowl_status_history (fowl_id, changed_at DESC);

-- 3a. One backfilled entry per existing bird (current registry state)
INSERT INTO fowl_status_history (fowl_id, field, old_value, new_value, reason, note, changed_at)
SELECT f.id, 'status', NULL, f.status,
       COALESCE(NULLIF(btrim(f.archive_reason), ''), NULLIF(btrim(f.death_reason), '')),
       'Backfilled from registry state (migration 20261006)',
       COALESCE(f.created_at, now())
  FROM fowl f
 WHERE NOT EXISTS (
   SELECT 1 FROM fowl_status_history h WHERE h.fowl_id = f.id
 );

-- ═══════════════════════════════════════════════════════════════════════════
-- 4. registry_options - user-editable lists
--    user_id IS NULL = global template (read-only for users);
--    user_id set     = farm's own entries ("Add Other" / edits).
--    Deactivate (is_active=false) instead of deleting once an option is used.
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS registry_options (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    TEXT,                        -- NULL = global template
  list_key   TEXT NOT NULL,               -- event_type | bird_class | post_match_condition | archive_reason | death_reason | retired_scope | location | match_type
  value      TEXT NOT NULL,               -- stored on the record
  label      TEXT NOT NULL,               -- shown in the UI
  local_label TEXT,                       -- optional Tagalog synonym (display only)
  sort_order INT NOT NULL DEFAULT 0,
  is_default BOOLEAN NOT NULL DEFAULT false,
  is_active  BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS registry_options_uq
  ON registry_options (COALESCE(user_id, '~global~'), list_key, value);
CREATE INDEX IF NOT EXISTS idx_registry_options_list
  ON registry_options (list_key, sort_order);

-- 4a. Global templates (seeds from the approved answer list)
INSERT INTO registry_options (user_id, list_key, value, label, sort_order, is_default)
SELECT NULL::text, v.list_key, v.value, v.label, v.ord, v.is_default
  FROM (VALUES
    ('event_type',           'Derby',                'Derby',                     1, true),
    ('event_type',           'Lusok',                'Lusok',                     2, false),
    ('bird_class',           'Chick',                'Chick',                     1, false),
    ('bird_class',           'Stag',                 'Stag',                      2, true),
    ('bird_class',           'Bull Stag',            'Bull Stag',                 3, false),
    ('bird_class',           'Cap',                  'Cap',                       4, false),
    ('post_match_condition', 'Fit / Recovered',      'Fit / Recovered',           1, true),
    ('post_match_condition', 'Injured',              'Injured',                   2, false),
    ('post_match_condition', 'Severely Injured',     'Severely Injured',          3, false),
    ('post_match_condition', 'Critically Injured',   'Critically Injured',        4, false),
    ('post_match_condition', 'Deceased',             'Deceased',                  5, false),
    ('archive_reason',       'sold',                 'Sold',                      1, false),
    ('archive_reason',       'transfer',             'Transfer / Borrowed',       2, false),
    ('archive_reason',       'inactive',             'Inactive',                  3, false),
    ('archive_reason',       'retired',              'Retired from fighting/circuit', 4, false),
    ('archive_reason',       'other',                'Other',                     5, false),
    ('death_reason',         'Injury during fight',  'Injury during fight',       1, false),
    ('death_reason',         'Illness',              'Illness',                   2, false),
    ('death_reason',         'Natural causes',       'Natural causes',            3, false),
    ('death_reason',         'Old age',              'Old age',                   4, false),
    ('death_reason',         'Slaughtered / cooked', 'Slaughtered / cooked',      5, false),
    ('death_reason',         'Other',                'Other',                     6, false),
    ('retired_scope',        'fighting',             'Fighting only',             1, true),
    ('retired_scope',        'breeding',             'Breeding only',             2, false),
    ('retired_scope',        'both',                 'Both (fighting and breeding)', 3, false),
    ('location',             'Hatch Ground',         'Hatch Ground',              1, false)
  ) AS v(list_key, value, label, ord, is_default)
ON CONFLICT DO NOTHING;

-- 4b. Per-farm location options seeded from locations already recorded
--     (keeps one farm's venues out of another farm's list)
INSERT INTO registry_options (user_id, list_key, value, label, sort_order)
SELECT DISTINCT m.user_id::text, 'location', m.location, m.location, 10
  FROM match m
 WHERE m.user_id IS NOT NULL
   AND m.location IS NOT NULL
   AND btrim(m.location) <> ''
ON CONFLICT DO NOTHING;

-- ═══════════════════════════════════════════════════════════════════════════
-- 5. user_settings - per-farm config keys (defaults live in app code;
--    a row here overrides the default)
--    Known keys: ranking_metric ('total_wins' | 'win_rate' | ...),
--                ranking_min_matches, match_location_required (bool),
--                family_headline ('offspring' | 'total_birds' | 'pairs')
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS user_settings (
  user_id    TEXT NOT NULL,
  key        TEXT NOT NULL,
  value      JSONB NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, key)
);

-- ═══════════════════════════════════════════════════════════════════════════
-- 6. match: loosened option constraints + lineage links
-- ═══════════════════════════════════════════════════════════════════════════

-- 6a. Bird class becomes an editable list (legacy Cock/Hen/Stag values stay valid)
ALTER TABLE match DROP CONSTRAINT IF EXISTS match_age_category_check;

-- 6b. Entries/caps may be any small count (and may be left blank)
ALTER TABLE match DROP CONSTRAINT IF EXISTS match_cock_count_check;
ALTER TABLE match
  ADD CONSTRAINT match_cock_count_check CHECK (cock_count IS NULL OR (cock_count >= 1 AND cock_count <= 99));

-- 6c. Post-match condition follows the editable condition list
--     (legacy values 'Severely Injured / Critical', 'Minor Injury',
--      'Deceased (Died from injuries)' remain storable)
ALTER TABLE match DROP CONSTRAINT IF EXISTS match_post_fight_condition_check;

-- 6d. Lineage links (entry_name / opponent stay as display snapshots)
ALTER TABLE match ADD COLUMN IF NOT EXISTS fowl_id     BIGINT;
ALTER TABLE match ADD COLUMN IF NOT EXISTS opponent_id BIGINT;

-- 6e. Backfill links ONLY on unambiguous same-user name matches (no guessing)
UPDATE match m
   SET fowl_id = sub.id
  FROM (
    SELECT user_id::text AS uid, name, min(id)::bigint AS id
      FROM fowl
     WHERE user_id IS NOT NULL AND name IS NOT NULL
     GROUP BY user_id::text, name
    HAVING count(*) = 1
  ) sub
 WHERE m.fowl_id IS NULL
   AND m.entry_name IS NOT NULL
   AND m.user_id IS NOT NULL
   AND sub.name = m.entry_name
   AND sub.uid = m.user_id::text;

UPDATE match m
   SET opponent_id = sub.id
  FROM (
    SELECT user_id::text AS uid, name, min(id)::bigint AS id
      FROM fowl
     WHERE user_id IS NOT NULL AND name IS NOT NULL
     GROUP BY user_id::text, name
    HAVING count(*) = 1
  ) sub
 WHERE m.opponent_id IS NULL
   AND m.opponent IS NOT NULL
   AND m.user_id IS NOT NULL
   AND sub.name = m.opponent
   AND sub.uid = m.user_id::text;

-- 6f. Foreign keys last (after backfill has cleaned the data)
ALTER TABLE match DROP CONSTRAINT IF EXISTS match_fowl_id_fkey;
ALTER TABLE match
  ADD CONSTRAINT match_fowl_id_fkey FOREIGN KEY (fowl_id) REFERENCES fowl(id) ON DELETE SET NULL;

ALTER TABLE match DROP CONSTRAINT IF EXISTS match_opponent_id_fkey;
ALTER TABLE match
  ADD CONSTRAINT match_opponent_id_fkey FOREIGN KEY (opponent_id) REFERENCES fowl(id) ON DELETE SET NULL;

-- ═══════════════════════════════════════════════════════════════════════════
-- 7. Row Level Security (owner CRUD + admin read, same style as
--    breeding_pairings / safety_incidents)
-- ═══════════════════════════════════════════════════════════════════════════

ALTER TABLE fowl_status_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE registry_options     ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_settings        ENABLE ROW LEVEL SECURITY;

-- 7a. fowl_status_history: reachable only through an owned bird; append-only
--     for owners (no UPDATE/DELETE policies), admin may read everything.
DROP POLICY IF EXISTS "fowl_status_history_owner_select" ON fowl_status_history;
CREATE POLICY "fowl_status_history_owner_select" ON fowl_status_history
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM fowl f
             WHERE f.id = fowl_status_history.fowl_id
               AND f.user_id = auth.uid()::text)
  );

DROP POLICY IF EXISTS "fowl_status_history_owner_insert" ON fowl_status_history;
CREATE POLICY "fowl_status_history_owner_insert" ON fowl_status_history
  FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM fowl f
             WHERE f.id = fowl_status_history.fowl_id
               AND f.user_id = auth.uid()::text)
  );

DROP POLICY IF EXISTS "fowl_status_history_admin_select" ON fowl_status_history;
CREATE POLICY "fowl_status_history_admin_select" ON fowl_status_history
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM profiles adm
             WHERE adm.id::uuid = auth.uid()
               AND (adm.is_admin = true OR adm.role = 'admin'))
  );

-- 7b. registry_options: templates for everyone, own rows editable
DROP POLICY IF EXISTS "registry_options_select" ON registry_options;
CREATE POLICY "registry_options_select" ON registry_options
  FOR SELECT USING (user_id IS NULL OR user_id = auth.uid()::text);

DROP POLICY IF EXISTS "registry_options_insert" ON registry_options;
CREATE POLICY "registry_options_insert" ON registry_options
  FOR INSERT WITH CHECK (user_id = auth.uid()::text);

DROP POLICY IF EXISTS "registry_options_update" ON registry_options;
CREATE POLICY "registry_options_update" ON registry_options
  FOR UPDATE USING (user_id = auth.uid()::text) WITH CHECK (user_id = auth.uid()::text);

DROP POLICY IF EXISTS "registry_options_delete" ON registry_options;
CREATE POLICY "registry_options_delete" ON registry_options
  FOR DELETE USING (user_id = auth.uid()::text);

DROP POLICY IF EXISTS "registry_options_admin_select" ON registry_options;
CREATE POLICY "registry_options_admin_select" ON registry_options
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM profiles adm
             WHERE adm.id::uuid = auth.uid()
               AND (adm.is_admin = true OR adm.role = 'admin'))
  );

-- 7c. user_settings: own farm config only, admin read-only
DROP POLICY IF EXISTS "user_settings_select" ON user_settings;
CREATE POLICY "user_settings_select" ON user_settings
  FOR SELECT USING (user_id = auth.uid()::text);

DROP POLICY IF EXISTS "user_settings_insert" ON user_settings;
CREATE POLICY "user_settings_insert" ON user_settings
  FOR INSERT WITH CHECK (user_id = auth.uid()::text);

DROP POLICY IF EXISTS "user_settings_update" ON user_settings;
CREATE POLICY "user_settings_update" ON user_settings
  FOR UPDATE USING (user_id = auth.uid()::text) WITH CHECK (user_id = auth.uid()::text);

DROP POLICY IF EXISTS "user_settings_delete" ON user_settings;
CREATE POLICY "user_settings_delete" ON user_settings
  FOR DELETE USING (user_id = auth.uid()::text);

DROP POLICY IF EXISTS "user_settings_admin_select" ON user_settings;
CREATE POLICY "user_settings_admin_select" ON user_settings
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM profiles adm
             WHERE adm.id::uuid = auth.uid()
               AND (adm.is_admin = true OR adm.role = 'admin'))
  );
